- name: Install Nginx
  ansible.builtin.apt:
    name: nginx
    state: present

- name: Apply Nginx configuration using template
  template:
    src: default.j2
    dest: /etc/nginx/sites-enabled/default
  notify:
    - Restart Nginx

- name: Flush handlers
  meta: flush_handlers

- name: Start Nginx service
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true

- name: Install Nginx Prometheus Exporter
  ansible.builtin.apt:
    name: prometheus-nginx-exporter
    state: present

- name: Start Nginx exporter service
  ansible.builtin.service:
    name: prometheus-nginx-exporter
    state: started
    enabled: true
