- name: Install Nginx
  ansible.builtin.apt:
    name: nginx
    state: present

- name: Apply Nginx configuration using template
  template:
    src: default.j2
    dest: /etc/nginx/sites-enabled/default
  notify:
    - Restart Nginx

- name: Start Nginx service
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true
