- name: Install HAProxy and HAProxy Exporter
  apt:
    name: 
      - haproxy
      - prometheus-haproxy-exporter
    state: present

- name: Config file for HAProxy
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  notify: restart haproxy

- name: Config file for exporter
  template:
    src: prometheus-haproxy-exporter.j2
    dest: /etc/default/prometheus-haproxy-exporter
  notify: prometheus-haproxy-exporter restart

- name: start HAProxy service and exporter
  service:
    name: "{{ item }}"
    state: started
  loop:
    - haproxy
    - prometheus-haproxy-exporter


- name: Add CNAME records for HAProxy
  nsupdate:
    key_name: "dns_update_key"
    key_algorithm: "hmac-sha256"
    key_secret: "{{ dns_update_key }}"
    server: "127.0.0.1"
    zone: "{{ mydomain }}."
    record: "{{ item.key }}"
    type: "CNAME"
    value: "{{ item.value }}"
  loop: "{{ haproxy_records | dict2items }}"
  run_once: True
  no_log: true
  notify: reload rndc
  delegate_to: "{{ groups['dns_masters'][0] }}"

