- name: Add InfluxData GPG key
  ansible.builtin.apt_key:
    url: https://repos.influxdata.com/influxdata-archive_compat.key
    state: present
    keyring: /etc/apt/keyrings/influxdata.gpg

- name: Add InfluxData repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/influxdata.gpg] https://repos.influxdata.com/debian stable main"
    state: present
    filename: influxdata

- name: Update APT cache
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600
  
- name: Install InfluxDB and Telegraf
  ansible.builtin.apt:
    name:
      - influxdb
      - telegraf
    state: present

- name: Telegraf configuration
  template:
    src: "telegraf.conf.j2"
    dest: "/etc/telegraf/telegraf.conf"
  notify:
    - Restart Telegraf

- name: Download InfluxDB Stats Exporter binary
  ansible.builtin.get_url:
    url: "https://github.com/carlpett/influxdb_stats_exporter/releases/download/v0.1.1/influx_stats_exporter_linux_amd64"
    dest: "/usr/local/bin/influxdb_stats_exporter"
    mode: '0755'

- name: Change ownership of the binary to prometheus user
  ansible.builtin.file:
    path: "/usr/local/bin/influxdb_stats_exporter"
    owner: prometheus
    group: prometheus
    mode: '0755'

- name: Deploy Prometheus InfluxDB Stats Exporter service file
  ansible.builtin.template:
    src: "prometheus_influxdb_stats_exporter.service.j2"
    dest: "/etc/systemd/system/prometheus-influxdb-stats-exporter.service"

- name: InfluxDB config file
  template:
    src: "influxdb.conf.j2"
    dest: "/etc/influxdb/influxdb.conf"
  notify:
    - Restart InfluxDB

- name: Reload Daemon
  systemd:
    daemon_reload: true

- name: Start and enable InfluxDB and Telegraf services
  ansible.builtin.service:
    name: "{{ item }}"
    state: started
    enabled: true
  loop:
    - influxdb
    - telegraf

- name: Start and enable Prometheus InfluxDB Stats Exporter service
  ansible.builtin.systemd:
    name: prometheus-influxdb-stats-exporter
    enabled: true
    state: started
