- name: Create directories for Grafana provisioning
  ansible.builtin.file:
    path: "/opt/grafana/provisioning/{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - dashboards
    - datasources

- name: Create Grafana configuration file from template
  ansible.builtin.template:
    src: grafana.ini.j2
    dest: /opt/grafana/grafana.ini
    mode: '0644'
  no_log: true
  notify:
    - Restart Grafana container

- name: Grafana Docker container
  community.docker.docker_container:
    image: grafana/grafana
    name: grafana
    published_ports: "{{ grafana_port }}:3000"
    volumes: /opt/grafana:/etc/grafana 

- name: Create Grafana configuration file from template
  ansible.builtin.template:
    src: dashboards.yaml.j2
    dest: /opt/grafana/provisioning/dashboards/default.yaml
  notify:
    - Restart Grafana container

- name: Create Grafana datasource provisioning file
  ansible.builtin.template:
    dest: /opt/grafana/provisioning/datasources/default.yaml
    src: datasources.yaml.j2
  notify:
    - Restart Grafana container

- name: Upload main.json to the server
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/opt/grafana/provisioning/dashboards/{{ item }}"
  notify: Restart Grafana container
  loop:
    - main.json
    - backups.json
    - syslog_dashboard.json
    - mysql.json
