- name: Create directories for Grafana provisioning
  ansible.builtin.file:
    path: "/opt/grafana/provisioning/{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - dashboards
    - datasources

- name: Create Grafana configuration file from template
  ansible.builtin.template:
    src: grafana.ini.j2
    dest: /opt/grafana/grafana.ini
    owner: 472
    group: 472
    mode: '0600'
  no_log: true
  notify:
    - Restart Grafana container

- name: Grafana Docker container
  community.docker.docker_container:
    image: grafana/grafana
    name: grafana
    published_ports: "{{ grafana_port }}:3000"
    volumes: /opt/grafana:/etc/grafana 
    restart_policy: "always"

- name: Create Grafana dashboard file
  ansible.builtin.template:
    src: dashboards.yaml.j2
    dest: /opt/grafana/provisioning/dashboards/default.yaml
  notify:
    - Restart Grafana container

- name: Create Grafana datasource provisioning file
  ansible.builtin.template:
    dest: /opt/grafana/provisioning/datasources/default.yaml
    src: datasources.yaml.j2
  notify:
    - Restart Grafana container

- name: Upload main.json to the server
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/opt/grafana/provisioning/dashboards/{{ item }}"
  notify: Restart Grafana container
  loop:
    - main.json
    - backups.json
    - syslog_dashboard.json
    - mysql.json

- name: Add CNAME records for Grafana
  nsupdate:
    key_name: "dns_update_key"
    key_algorithm: "hmac-sha256"
    key_secret: "{{ dns_update_key }}"
    server: "127.0.0.1"
    zone: "{{ mydomain }}."
    record: "{{ item.key }}"
    type: "CNAME"
    value: "{{ item.value }}"
  loop: "{{ grafana_records | dict2items }}"
  run_once: True
  no_log: true
  notify: reload rndc
  delegate_to: "{{ groups['dns_masters'][0] }}"

