- name: Install uWSGI packages
  ansible.builtin.apt:
    name:
      - uwsgi
      - uwsgi-plugin-python3
    state: present
  
- name: Copy "agama.ini" file
  copy: 
    src: agama.ini
    dest: /etc/uwsgi/apps-enabled/agama.ini
  notify:
    - Restart uWSG

- name: uWSGI service
  ansible.builtin.service:
    name: uwsgi
    state: started
    enabled: true
