---
- name: Initial setup
  hosts: all
  gather_facts: yes
  roles:
    - init
  tags: i



- name: DNS Servers
  hosts: dns_servers
  roles:
    - bind
  tags: dns

- name: Resolve
  hosts: all
  roles:
    - resolver
  tags: r

- name: Web Servers
  hosts: web_servers
  roles:
    - agama
    - uwsgi
    - nginx
  tags: w

- name: Database server
  hosts: db_servers
  roles:
    - mysql
  tags: db

- name: Prometheus server
  hosts: prometheus_servers
  roles:
    - prometheus
    - nginx
  tags: p

- name: Grafana server
  hosts: grafana_servers
  roles:
    - grafana
  tags: g
