---
- name: Initial setup
  hosts: all
  gather_facts: yes
  roles:
    - init
  tags: i



- name: DNS Servers
  hosts: dns_servers
  roles:
    - bind

- name: Resolve
  hosts: all
  roles:
    - resolver

- name: Web Servers
  hosts: web_servers
  roles:
    - agama
    - uwsgi
    - nginx

- name: Database server
  hosts: db_servers
  roles:
    - mysql

- name: Prometheus server
  hosts: prometheus_servers
  roles:
    - prometheus
    - nginx
  tags: p
