{
 "title": "Main",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "A DNS Queries per Minute",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(bind_resolver_queries_total{type=\"A\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Bind9 Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"bind9\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "InfluxDb health ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "influxdb_exporter_stats_query_success",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Nginx Requests per Minute",
   "type": "timeseries",
   "description": "Requests per Minute",
   "gridPos": { "h": 6, "w": 6, "x": 11, "y": 0 },
   "targets": [
    {
     "expr": "rate(nginx_http_requests_total[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "HAProxy Server Up Status for Each Container",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "haproxy_server_up", "legendFormat": "{{instance}}:{{server}}" }
   ]
  },
  {
   "title": "MySQL Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 6, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"mysql\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "MySQL  SELECT Commands per Minute",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "rate(mysql_global_status_commands_total{command=\"select\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory Consumption on VMs",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 11, "y": 6 },
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "HAProxy Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 17, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "haproxy_up", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "InfluxDB write rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 6, "y": 7 },
   "targets": [
    { "expr": "influxdb_write_write_ok", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Keepalived Up Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 17, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "keepalived_up", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Item count for all discovered Agamas",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT *\nFROM \"agama-stats\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Current number of items in my Agama",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT *\nFROM \"agama-stats\" \nWHERE \"name\" = 'mjeyhun-1' \n"
    }
   ]
  },
  {
   "title": "CPU Utilization on VMs",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 11, "y": 12 },
   "targets": [
    {
     "expr": "100 - (rate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Keepalived VRRP State",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 17, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "keepalived_vrrp_state", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Nginx Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"nginx\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}