{
 "title": "MySQL",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "MySQL replication IO Thread Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_slave_status_slave_io_running",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "MySQL replication SQL Thread Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_slave_status_slave_sql_running",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "MySQL server id",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_global_variables_server_id",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "MySQL status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"mysql\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "MySQL  SELECT Commands per Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "rate(mysql_global_status_commands_total{command=\"select\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "MySQL Read-Only Status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_global_variables_read_only",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}