- name: Create /opt/agama directory
  ansible.builtin.file:
    path: /opt/agama
    state: directory

- name: Download Agama files
  get_url:
    url: "{{ item.url }}"
    dest: "/opt/agama/{{ item.dest }}"
  loop:
    - { url: "https://raw.githubusercontent.com/hudolejev/agama/refs/heads/master/agama.py", dest: "agama.py" }
    - { url: "https://raw.githubusercontent.com/hudolejev/agama/refs/heads/master/Dockerfile", dest: "Dockerfile" }

- name: Build Agama Docker image
  community.docker.docker_image:
    name: agama
    source: build
    build:
      path: /opt/agama

- name: Start Agama Docker container
  community.docker.docker_container:
    name: "agama_{{ item }}"
    image: agama
    state: started
    published_ports:
      - "{{ agama_port + item - 1 }}:8000"  
    env:
      AGAMA_DATABASE_URI: "mysql+pymysql://{{ mysql_user }}:{{ mysql_password }}@{{ mysql_host }}/{{ mysql_database }}"
    volumes:
      - /opt/agama:/opt/agama
    restart_policy: "always"
  no_log: true
  loop: "{{ range(1, number_of_containers + 1) | list }}"

- name: Add CNAME records for Prometheus
  nsupdate:
    key_name: "dns_update_key"
    key_algorithm: "hmac-sha256"
    key_secret: "{{ dns_update_key }}"
    server: "127.0.0.1"
    zone: "{{ mydomain }}."
    record: "{{ item.key }}"
    type: "CNAME"
    value: "{{ item.value }}"
  loop: "{{ web_servers_records | dict2items }}"
  run_once: True
  no_log: true
  notify: reload rndc
  delegate_to: "{{ groups['dns_masters'][0] }}"

