- name: Install MySQL server
  apt:
    name: mysql-server
    state: present
    update_cache: yes

- name: Ensure MySQL service is started and enabled
  service:
    name: mysql
    state: started
    enabled: yes

#- name: Notify MySQL restart
#  debug:
#    msg: "Restarting MySQL to apply configuration changes"
#  notify: Restart MySQL

- name: MySQL override.cnf
  template:
    src: override.cnf.j2
    dest: /etc/mysql/mysql.conf.d/override.cnf
  notify: Restart MySQL

- name: Install Python MySQL library
  apt:
    name: python3-pymysql
    state: present
    update_cache: yes

- name: MySQL database
  community.mysql.mysql_db:
    name: "{{ mysql_database }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: MySQL user
  community.mysql.mysql_user:
    name: "{{ mysql_user }}"
    password: "{{ mysql_password }}"
    host: "%"
    priv: "{{ mysql_database }}.*:ALL"
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: MYSQL exporter
  apt:
    name: prometheus-mysqld-exporter
    state: present

- name: Ensure Prometheus MYSQL Exporter is started and enabled
  ansible.builtin.systemd:
    name: prometheus-mysqld-exporter
    state: started
    enabled: true

- name: Create MySQL user for the exporter
  community.mysql.mysql_user:
    name: "{{ mysql_exporter_username }}"
    password: "{{ mysql_exporter_password }}"
    priv: "*.*:PROCESS,REPLICATION CLIENT"
    host: "%"
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Cnf files for exporter
  template:
    dest: /var/lib/prometheus/.my.cnf
    src: my.cnf.j2
  no_log: true 
