- name: Restart Telegraf
  service:
    name: telegraf
    state: restarted

- name: Restart InfluxDB
  service:
    name: influxdb
    state: restarted

- name: restart cron
  service:
    name: cron
    state: restarted

- name: reload rndc
  command: rndc reload
