- name: restart haproxy
  service:
    name: haproxy
    state: restarted

- name: prometheus-haproxy-exporter restart
  service:
    name: prometheus-haproxy-exporter
    state: restarted

- name: reload rndc
  command: rndc reload
