- name: install prometheus
  ansible.builtin.apt:
    name: prometheus
    state: present

- name: Ensure Prometheus service is enabled and started
  ansible.builtin.service:
    name: prometheus
    state: started
    enabled: true

- name: Apply Prometheus default configuration from template
  ansible.builtin.template:
    src: prometheus.j2
    dest: /etc/default/prometheus
  notify: Restart Prometheus.j2

- name: Update Prometheus config
  ansible.builtin.template:
    src: prometheus.yml.j2  
    dest: /etc/prometheus/prometheus.yml
  notify: Restart Prometheus

- name: Add CNAME records for Prometheus
  nsupdate:
    key_name: "dns_update_key"
    key_algorithm: "hmac-sha256"
    key_secret: "{{ dns_update_key }}"
    server: "127.0.0.1"
    zone: "{{ mydomain }}."
    record: "{{ item.key }}"
    type: "CNAME"
    value: "{{ item.value }}"
  loop: "{{ prometheus_records | dict2items }}"
  run_once: True
  no_log: true
  notify: reload rndc
  delegate_to: "{{ groups['dns_masters'][0] }}"
