- name: Install fping
  apt:
    name: fping
    state: present

- name: Ensure agama-client user exists
  ansible.builtin.user:
    name: agama-client
    state: present
    system: yes
    create_home: no
    shell: /bin/bash

- name: Copy agama-client script to /usr/local/bin
  template:
    src: "agama-client.sh.j2"
    dest: "/usr/local/bin/agama-client"
    mode: "0755"

- name: Ensure /etc/agama-client directory exists
  file:
    path: /etc/agama-client
    state: directory

- name: Copy agama-client.conf to /etc/agama-client
  template:
    src: "agama-client.conf.j2"
    dest: "/etc/agama-client/agama-client.conf"
#  notify:
#    - Restart agama-client

- name: Create systemd service file for agama-client
  template:
    src: "agama-client.service.j2"
    dest: "/etc/systemd/system/agama-client.service"
#  notify:
#  - Restart agama-client

- name: Reload systemd daemon
  systemd:
    daemon_reload: true

- name: Enable and start agama-client service
  systemd:
    name: agama-client.service
    enabled: true
    state: started
